// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCES:
 *     DefaultEventCreated.avsc
 *     EventHeader.avsc
 *     NewEvent2.avsc
 */
package my_sandbox_sandbox_events

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v9/compiler"
	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

var _ = fmt.Printf

type DefaultEventCreated struct {
	Header EventHeader `json:"header"`
	// Example: This is a sample attribute, please edit.
	Sample string `json:"sample"`

	NewField1 *UnionNullString `json:"newField1"`
}

const DefaultEventCreatedAvroCRC64Fingerprint = "\xc0\xedNq\xdcg\xc90"

func NewDefaultEventCreated() DefaultEventCreated {
	r := DefaultEventCreated{}
	r.Header = NewEventHeader()

	r.NewField1 = NewUnionNullString()

	r.NewField1 = nil
	return r
}

func DeserializeDefaultEventCreated(r io.Reader) (DefaultEventCreated, error) {
	t := NewDefaultEventCreated()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeDefaultEventCreatedFromSchema(r io.Reader, schema string) (DefaultEventCreated, error) {
	t := NewDefaultEventCreated()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeDefaultEventCreated(r DefaultEventCreated, w io.Writer) error {
	var err error
	err = writeEventHeader(r.Header, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Sample, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.NewField1, w)
	if err != nil {
		return err
	}
	return err
}

func (r DefaultEventCreated) Serialize(w io.Writer) error {
	return writeDefaultEventCreated(r, w)
}

func (r DefaultEventCreated) Schema() string {
	return "{\"fields\":[{\"doc\":\"\",\"name\":\"header\",\"type\":{\"doc\":\"The below fields include header information and should be included on every event in the DESP. Inspired by: https://github.com/cloudevents/spec/blob/v0.2/spec.md\",\"fields\":[{\"doc\":\"A unique identifier of the event - for example, a randomly generated GUID\",\"name\":\"id\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"}},{\"doc\":\"Time the event occurred in milliseconds since epoch, UTC timezone.\",\"name\":\"time\",\"type\":\"long\"},{\"doc\":\"Type of occurrence which has happened. Reference the domain.event registered in schema-registry.\",\"name\":\"type\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"}},{\"doc\":\"Service that produced the event. Future: reference to producer registry.\",\"name\":\"source\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"}}],\"name\":\"EventHeader\",\"namespace\":\"com.kroger.desp.commons.desp.sandbox\",\"type\":\"record\"}},{\"doc\":\"Example: This is a sample attribute, please edit.\",\"name\":\"sample\",\"type\":\"string\"},{\"default\":null,\"doc\":\"\",\"name\":\"newField1\",\"type\":[\"null\",{\"avro.java.string\":\"String\",\"type\":\"string\"}]}],\"name\":\"com.kroger.desp.events.desp.sandbox.DefaultEventCreated\",\"type\":\"record\"}"
}

func (r DefaultEventCreated) SchemaName() string {
	return "com.kroger.desp.events.desp.sandbox.DefaultEventCreated"
}

func (_ DefaultEventCreated) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ DefaultEventCreated) SetInt(v int32)       { panic("Unsupported operation") }
func (_ DefaultEventCreated) SetLong(v int64)      { panic("Unsupported operation") }
func (_ DefaultEventCreated) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ DefaultEventCreated) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ DefaultEventCreated) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ DefaultEventCreated) SetString(v string)   { panic("Unsupported operation") }
func (_ DefaultEventCreated) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *DefaultEventCreated) Get(i int) types.Field {
	switch i {
	case 0:
		r.Header = NewEventHeader()

		return &types.Record{Target: &r.Header}
	case 1:
		return &types.String{Target: &r.Sample}
	case 2:
		r.NewField1 = NewUnionNullString()

		return r.NewField1
	}
	panic("Unknown field index")
}

func (r *DefaultEventCreated) SetDefault(i int) {
	switch i {
	case 2:
		r.NewField1 = nil
		return
	}
	panic("Unknown field index")
}

func (r *DefaultEventCreated) NullField(i int) {
	switch i {
	case 2:
		r.NewField1 = nil
		return
	}
	panic("Not a nullable field index")
}

func (_ DefaultEventCreated) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ DefaultEventCreated) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ DefaultEventCreated) Finalize()                        {}

func (_ DefaultEventCreated) AvroCRC64Fingerprint() []byte {
	return []byte(DefaultEventCreatedAvroCRC64Fingerprint)
}

func (r DefaultEventCreated) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["header"], err = json.Marshal(r.Header)
	if err != nil {
		return nil, err
	}
	output["sample"], err = json.Marshal(r.Sample)
	if err != nil {
		return nil, err
	}
	output["newField1"], err = json.Marshal(r.NewField1)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *DefaultEventCreated) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["header"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Header); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for header")
	}
	val = func() json.RawMessage {
		if v, ok := fields["sample"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Sample); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for sample")
	}
	val = func() json.RawMessage {
		if v, ok := fields["newField1"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.NewField1); err != nil {
			return err
		}
	} else {
		r.NewField1 = NewUnionNullString()

		r.NewField1 = nil
	}
	return nil
}
